// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	Account
	Res
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	IdCard   string `protobuf:"bytes,2,opt,name=idCard" json:"idCard,omitempty"`
	Gender   int32  `protobuf:"varint,3,opt,name=gender" json:"gender,omitempty"`
	Zip      string `protobuf:"bytes,4,opt,name=zip" json:"zip,omitempty"`
	Address  string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	Birthday string `protobuf:"bytes,6,opt,name=birthday" json:"birthday,omitempty"`
	Mobile   string `protobuf:"bytes,7,opt,name=mobile" json:"mobile,omitempty"`
	Tel      string `protobuf:"bytes,8,opt,name=tel" json:"tel,omitempty"`
	Fax      string `protobuf:"bytes,9,opt,name=fax" json:"fax,omitempty"`
	Email    string `protobuf:"bytes,10,opt,name=email" json:"email,omitempty"`
	Nation   string `protobuf:"bytes,11,opt,name=nation" json:"nation,omitempty"`
	Created  string `protobuf:"bytes,12,opt,name=created" json:"created,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *Account) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *Account) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *Account) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Account) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *Account) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Account) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *Account) GetFax() string {
	if m != nil {
		return m.Fax
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetNation() string {
	if m != nil {
		return m.Nation
	}
	return ""
}

func (m *Account) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type Res struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Err  string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *Res) Reset()                    { *m = Res{} }
func (m *Res) String() string            { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()               {}
func (*Res) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Res) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Res) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Res) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*Res)(nil), "account.Res")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AccountOp service

type AccountOpClient interface {
	AddAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Res, error)
}

type accountOpClient struct {
	cc *grpc.ClientConn
}

func NewAccountOpClient(cc *grpc.ClientConn) AccountOpClient {
	return &accountOpClient{cc}
}

func (c *accountOpClient) AddAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := grpc.Invoke(ctx, "/account.AccountOp/AddAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountOp service

type AccountOpServer interface {
	AddAccount(context.Context, *Account) (*Res, error)
}

func RegisterAccountOpServer(s *grpc.Server, srv AccountOpServer) {
	s.RegisterService(&_AccountOp_serviceDesc, srv)
}

func _AccountOp_AddAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountOpServer).AddAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountOp/AddAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountOpServer).AddAccount(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountOp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountOp",
	HandlerType: (*AccountOpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAccount",
			Handler:    _AccountOp_AddAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0x41, 0x6a, 0xf3, 0x30,
	0x10, 0x85, 0xff, 0xc4, 0xb1, 0x1d, 0xcf, 0x9f, 0x42, 0x10, 0xa5, 0x0c, 0x59, 0x05, 0xaf, 0xb2,
	0xf2, 0xa2, 0x5d, 0x96, 0x2e, 0x42, 0x0f, 0x50, 0xd0, 0x0d, 0x64, 0x6b, 0x92, 0x0a, 0x6c, 0xcb,
	0xc8, 0x2a, 0xa4, 0xbd, 0x49, 0x6f, 0x5b, 0x46, 0x92, 0xb3, 0x7b, 0xdf, 0x67, 0xf3, 0x24, 0x9e,
	0xe0, 0x41, 0x75, 0x9d, 0xfd, 0x1a, 0x7d, 0x33, 0x39, 0xeb, 0xad, 0x28, 0x13, 0xd6, 0xbf, 0x6b,
	0x28, 0xcf, 0x31, 0x0b, 0x01, 0x9b, 0x51, 0x0d, 0x84, 0xab, 0xe3, 0xea, 0x54, 0xc9, 0x90, 0xc5,
	0x13, 0x14, 0x46, 0xbf, 0x2b, 0xa7, 0x71, 0x1d, 0x6c, 0x22, 0xf6, 0x57, 0x1a, 0x35, 0x39, 0xcc,
	0x8e, 0xab, 0x53, 0x2e, 0x13, 0x89, 0x3d, 0x64, 0x3f, 0x66, 0xc2, 0x4d, 0xf8, 0x99, 0xa3, 0x40,
	0x28, 0x95, 0xd6, 0x8e, 0xe6, 0x19, 0xf3, 0x60, 0x17, 0x14, 0x07, 0xd8, 0xb6, 0xc6, 0xf9, 0x4f,
	0xad, 0xbe, 0xb1, 0x08, 0x9f, 0xee, 0xcc, 0xfd, 0x83, 0x6d, 0x4d, 0x4f, 0x58, 0xc6, 0x73, 0x23,
	0x71, 0xbf, 0xa7, 0x1e, 0xb7, 0xb1, 0xdf, 0x53, 0xcf, 0xe6, 0xa2, 0x6e, 0x58, 0x45, 0x73, 0x51,
	0x37, 0xf1, 0x08, 0x39, 0x0d, 0xca, 0xf4, 0x08, 0xc1, 0x45, 0xe0, 0xc6, 0x51, 0x79, 0x63, 0x47,
	0xfc, 0x1f, 0x1b, 0x23, 0xf1, 0xfd, 0x3a, 0x47, 0xca, 0x93, 0xc6, 0x5d, 0xbc, 0x5f, 0xc2, 0xfa,
	0x0d, 0x32, 0x49, 0x33, 0xcf, 0xd2, 0x59, 0x1d, 0x67, 0xc9, 0x65, 0xc8, 0x7c, 0xe8, 0x30, 0x5f,
	0xd3, 0x26, 0x1c, 0xd9, 0x90, 0x8b, 0x6b, 0x54, 0x92, 0xe3, 0xf3, 0x2b, 0x54, 0x69, 0xd9, 0x8f,
	0x49, 0x34, 0x00, 0x67, 0xad, 0x97, 0xa5, 0xf7, 0xcd, 0xf2, 0x1c, 0xc9, 0x1c, 0x76, 0x77, 0x23,
	0x69, 0xae, 0xff, 0xb5, 0x45, 0x78, 0xa7, 0x97, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0x81,
	0xd4, 0x6d, 0xb8, 0x01, 0x00, 0x00,
}
